# Generated by Django 4.2.4 on 2023-09-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_c_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='c_slug',
            new_name='slug',
        ),
    ]
